{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kable-core/0.9.3-l2cap.1/kable-core-0.9.3-l2cap.1.module",
    "group": "com.juul.kable",
    "module": "kable-core",
    "version": "0.9.3-l2cap.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core.aar",
          "url": "kable-core-android-0.9.3-l2cap.1.aar",
          "size": 427442,
          "sha512": "a1e79111e15f518b123de72f1964186f27e0d198fc39f13b265b9c34feb24db354b8002d5a02621b570c89f48918ff88a62461598f4ea8f47cf1acf1de57d5e5",
          "sha256": "b529d356db302fd9cced63c419af6bea919fdc7213b6ea00314f6ecb33e2b2d7",
          "sha1": "10228c555a1ccd1182b14ba19d86aaa415de4e64",
          "md5": "baa49b5cd9a84a47caeaab071e0ac39d"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "com.juul.tuulbox",
          "module": "coroutines",
          "version": {
            "requires": "8.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core.aar",
          "url": "kable-core-android-0.9.3-l2cap.1.aar",
          "size": 427442,
          "sha512": "a1e79111e15f518b123de72f1964186f27e0d198fc39f13b265b9c34feb24db354b8002d5a02621b570c89f48918ff88a62461598f4ea8f47cf1acf1de57d5e5",
          "sha256": "b529d356db302fd9cced63c419af6bea919fdc7213b6ea00314f6ecb33e2b2d7",
          "sha1": "10228c555a1ccd1182b14ba19d86aaa415de4e64",
          "md5": "baa49b5cd9a84a47caeaab071e0ac39d"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kable-core-android-sources.jar",
          "url": "kable-core-android-0.9.3-l2cap.1-sources.jar",
          "size": 82164,
          "sha512": "978ac93b919a495642f2e41152f436dad01599537eaf0d4a4177b52fc1115ca93af9203a044fcf203b7c59ec16d8f8528ee31439a10f87ecfa02cbb65faabb95",
          "sha256": "821ce6036eba9676cb7c935cd9a07f1604b5776c06f49dcf28f750e8eee00916",
          "sha1": "39432c2ac848e04427d2e18522494cbc38241eec",
          "md5": "70227448615ef510fd83073f677bf004"
        }
      ]
    }
  ]
}
