{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kable-core/0.9.3-l2cap.1/kable-core-0.9.3-l2cap.1.module",
    "group": "com.juul.kable",
    "module": "kable-core",
    "version": "0.9.3-l2cap.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core-watchosArm64Main.klib",
          "url": "kable-core-watchosarm64-0.9.3-l2cap.1.klib",
          "size": 317606,
          "sha512": "b95a9f2a18a798803184466f0c6bd9c34886ae313ccfef2331fdc3c74a1d289c8b3c7f3125fbdeee5ad0e996113b4e0f43b7af1c8912194ded59ff98b931d8cd",
          "sha256": "d8cbf2e53145823117653065a6dcf9584161972d2e2ea684fb43f40c003e4b9a",
          "sha1": "243dd9882f3b536784ec83becb8c089ddf258d40",
          "md5": "025036940fc43ddb57e98fb4f551d6ac"
        }
      ]
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kable-core-watchosarm64-sources.jar",
          "url": "kable-core-watchosarm64-0.9.3-l2cap.1-sources.jar",
          "size": 79243,
          "sha512": "63afce872f7ec093ce01f46692da1bf45a09a5d3b0a6314db543ecda5397c27f24e7a7d7f6e9cd54859cea865f702747ac128fbc00325843bb2866290f86dcc1",
          "sha256": "a81e3ac0742d11c83a99f52fe2cefd3a35e17cc7996b859d877abd4d870b29b2",
          "sha1": "cfa83fba594c53bbe1c49f5a2321ab5885a8cc6f",
          "md5": "9d0fb15718f6d9a25443b92e67359505"
        }
      ]
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core-watchosarm64-metadata.jar",
          "url": "kable-core-watchosarm64-0.9.3-l2cap.1-metadata.jar",
          "size": 29990,
          "sha512": "a28a951a6737cc4411db7c536eb13bf55f176f06f2daee6276332debb010761513d00f63eefb4448e89e07738c0e6f1a4d1b6a7d38cbe1e5b660a225754b919b",
          "sha256": "1b057844bdc75867bf9358b01ca04227db9314442a696511bdc77bd3deaa04fa",
          "sha1": "8cead6de330d752b674a5dc662e1dedcc2abe2aa",
          "md5": "0cdd9cfc973a31d6a8f712b206f064bd"
        }
      ]
    }
  ]
}
