{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kable-core/0.9.3-l2cap.1/kable-core-0.9.3-l2cap.1.module",
    "group": "com.juul.kable",
    "module": "kable-core",
    "version": "0.9.3-l2cap.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core-iosX64Main.klib",
          "url": "kable-core-iosx64-0.9.3-l2cap.1.klib",
          "size": 317618,
          "sha512": "e02ad6727600bc6a957037877f5b7fb1057f4101290f62ec77d23baa9b6090a8cc22e84ac1dfcede9b9c2769574add07538f2190e3899d607006f5ea92accfc4",
          "sha256": "b60e6c478bd11925a2ceb475623ad5383344d525c35d6a9fe1f11104035194ed",
          "sha1": "3ca8d39a6af757096d219ff295ce55a46ca9b43f",
          "md5": "422329f6df5c899898d39fb2c3484eda"
        }
      ]
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kable-core-iosx64-sources.jar",
          "url": "kable-core-iosx64-0.9.3-l2cap.1-sources.jar",
          "size": 79243,
          "sha512": "63afce872f7ec093ce01f46692da1bf45a09a5d3b0a6314db543ecda5397c27f24e7a7d7f6e9cd54859cea865f702747ac128fbc00325843bb2866290f86dcc1",
          "sha256": "a81e3ac0742d11c83a99f52fe2cefd3a35e17cc7996b859d877abd4d870b29b2",
          "sha1": "cfa83fba594c53bbe1c49f5a2321ab5885a8cc6f",
          "md5": "9d0fb15718f6d9a25443b92e67359505"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.33.0"
          }
        }
      ],
      "files": [
        {
          "name": "kable-core-iosx64-metadata.jar",
          "url": "kable-core-iosx64-0.9.3-l2cap.1-metadata.jar",
          "size": 29990,
          "sha512": "a28a951a6737cc4411db7c536eb13bf55f176f06f2daee6276332debb010761513d00f63eefb4448e89e07738c0e6f1a4d1b6a7d38cbe1e5b660a225754b919b",
          "sha256": "1b057844bdc75867bf9358b01ca04227db9314442a696511bdc77bd3deaa04fa",
          "sha1": "8cead6de330d752b674a5dc662e1dedcc2abe2aa",
          "md5": "0cdd9cfc973a31d6a8f712b206f064bd"
        }
      ]
    }
  ]
}
